# Generated by Django 5.1 on 2024-08-27 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='url_img',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='url_img',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
