# Generated by Django 5.1 on 2024-08-29 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_category_url_img_product_url_img'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='category',
            table='categories',
        ),
    ]
